### ISSUE TITLE
请求添加自定义的音乐块模组

### ISSUE THREAD

**Issue by link1412** [Becks723/StardewMods#2]
非常喜欢您的 n 网 6971 模组，但该模组目前已隐藏了，请问可以继续支持么。
若不考虑兼容星露谷 1.6，恳请能够开放旧版本匹配的模组。

**Comment by Becks723** [comment]
谢谢你还记得这个模组哈哈哈。不过它是2020年6月份写成的，那时候还没1.5吧；然后制作技艺拙劣，导致整个模组有将近200mb。如果开放，你可能得用1.4版本玩了……要兼容的话，得重写了，基本上就这个情况。

**Comment by link1412** [comment]
> 谢谢你还记得这个模组哈哈哈。不过它是2020年6月份写成的，那时候还没1.5吧；然后制作技艺拙劣，导致整个模组有将近200mb。如果开放，你可能得用1.4版本玩了……要兼容的话，得重写了，基本上就这个情况。

下午好，之前开放时下载过此 MOD，目前我有备份，也有星露谷1.4的备份（当然后面也补票玩了1.5 和 1.6，尊重劳动果实）。
曾拜读过此 MOD 源码，奈何我是 WEB 开发者，阅读 C# 程序比较吃力，暂时没有维护的能力。

若暂不考虑维护的话，请问我可以使用此 MOD 制作一些音乐视频，并将其发布在短视频平台（bilibili）么，**不会参与任何商用成分**，仅为分享基于此 MOD 制作的一些有趣视频。

**Comment by Becks723** [comment]
不要紧，视频你可以随便做好了，简介标一下就好。
